# Generated by Django 2.1.2 on 2018-10-18 17:08

import authors.apps.authentication.social_login.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_auth_id',
            field=models.CharField(default=authors.apps.authentication.social_login.utils.create_unique_social_id_number, max_length=255),
        ),
    ]
