# Generated by Django 2.1.2 on 2018-10-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20181018_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
