# Generated by Django 2.1.2 on 2018-10-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_reading_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='article',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='reaction',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='article',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='favourite_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='reading_time',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Impression',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
